name: moroorak_flutter
description: Moroorak - Accident Report App for Sudan

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  image_picker: ^1.0.7
  geolocator: ^10.0.0
  google_fonts: ^6.3.2
  flutter_spinkit: ^5.2.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  path: ^1.8.3
  investigator_web:
    path: investigator_web
  shared_preferences: ^2.5.3
  firebase_core: 4.2.1
  firebase_messaging: 16.0.4
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
