name: investigator_web
description: Moroorak - Investigator Web App

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  supabase_flutter: ^2.10.3
  google_fonts: ^6.3.2
  flutter_spinkit: ^5.2.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  path: ^1.8.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
